using System;
using System.Collections.Generic;
using System.Globalization;
using System.Threading;

namespace YourNamespace
{
    public static class LocalizationManager
    {
        private static Dictionary<string, Dictionary<string, string>> languageResources = new Dictionary<string, Dictionary<string, string>>
        {
            ["ru-RU"] = new Dictionary<string, string>
            {
                ["AppName"] = "Текстовый редактор",
                ["CodeGroup"] = "Код для выполнения",
                ["ResultGroup"] = "Результат выполнения",
                ["FileMenu"] = "Файл",
                ["EditMenu"] = "Правка",
                ["HelpMenu"] = "Справка",
                ["ViewMenu"] = "Вид",
                ["CreateMenu"] = "Создать",
                ["OpenMenu"] = "Открыть",
                ["SaveMenu"] = "Сохранить",
                ["SaveAsMenu"] = "Сохранить как...",
                ["CloseMenu"] = "Закрыть",
                ["ExitMenu"] = "Выход",
                ["UndoMenu"] = "Отменить",
                ["RedoMenu"] = "Повторить",
                ["CutMenu"] = "Вырезать",
                ["CopyMenu"] = "Копировать",
                ["PasteMenu"] = "Вставить",
                ["DeleteMenu"] = "Удалить",
                ["SelectAllMenu"] = "Выделить все",
                ["UserGuideMenu"] = "Руководство пользователя",
                ["AboutMenu"] = "О программе",
                ["FontSizeMenu"] = "Размер шрифта",
                ["LanguageMenu"] = "Язык интерфейса",
                ["StartMenu"] = "Пуск",
                ["AnalyzeTooltip"] = "Запустить анализ",
                ["TokensGrid_Code"] = "Условный код",
                ["TokensGrid_Type"] = "Тип лексемы",
                ["TokensGrid_Lexeme"] = "Лексема",
                ["TokensGrid_Location"] = "Местоположение",
                ["ErrorsGrid_Fragment"] = "Неверный фрагмент",
                ["ErrorsGrid_Location"] = "Местоположение",
                ["ErrorsGrid_Description"] = "Описание",
                ["ErrorsSummaryTotal"] = "Общее количество ошибок:",
                ["LocationLine"] = "строка",
                ["LocationPosition"] = "позиция",
                ["AnalysisSuccess"] = "УСПЕХ",
                ["AnalysisProcessedLexemes"] = "Обработано {0} лексем",
                ["Lexer_InvalidCharacter"] = "Недопустимый символ: '{0}'",
                ["TokenType_Keyword"] = "ключевое слово",
                ["TokenType_Identifier"] = "идентификатор",
                ["TokenType_Number"] = "число",
                ["TokenType_Operator"] = "оператор",
                ["TokenType_Separator"] = "разделитель",
                ["TokenType_Whitespace"] = "пробел",
                ["TokenType_Error"] = "ошибка",
                ["TokenType_Unknown"] = "неизвестно",
                ["Parser_ExpectedPrefix"] = "Ожидалось",
                ["Parser_ExpectedIdentifier"] = "идентификатор",
                ["Parser_ExpectedFloatNumber"] = "вещественное число",
                ["Parser_EmptyInput"] = "Пустой входной поток",
                ["Parser_WhitespaceOnlyInput"] = "Пустой входной поток (только пробелы)",
                ["Parser_InvalidFragment"] = "Неверный фрагмент",
                ["Parser_InvalidNumberFormat"] = "Неверный формат числа",
                ["Parser_ExpectedDigitAfterDecimal"] = "Ожидалась цифра после десятичной точки",
                ["Parser_ExpectedDigitAfterExponent"] = "Ожидалась цифра после экспоненты",
                ["ConfirmationExit"] = "Подтверждение выхода",
                ["ConfirmationClose"] = "Подтверждение закрытия",
                ["UnsavedChangesTab"] = "У вас есть несохраненные изменения во вкладке",
                ["SaveBeforeExit"] = "Сохранить перед выходом?",
                ["SaveBeforeClose"] = "Сохранить перед закрытием?",
                ["ExitQuestion"] = "Выйти?",
                ["UnsavedChangesPromptExit"] = "У вас есть несохраненные изменения во вкладке '{0}'. Сохранить перед выходом?",
                ["UnsavedChangesPromptClose"] = "У вас есть несохраненные изменения во вкладке '{0}'. Сохранить перед закрытием?",
                ["UserGuideTitle"] = "Руководство пользователя",
                ["FunctionsList"] = "Реализованные функции:",
                ["CreateOpenSave"] = "- Создание, открытие, сохранение файлов",
                ["TextOperations"] = "- Операции с текстом: отмена/возврат, вырезание, копирование, вставка, удаление",
                ["SelectAll"] = "- Выделение всего текста",
                ["FontSizeChange"] = "- Изменение размера шрифта",
                ["LineNumbering"] = "- Нумерация строк в окне редактирования",
                ["MultiDocs"] = "- Работа с несколькими документами через вкладки",
                ["AdaptiveInterface"] = "- Адаптивный интерфейс с возможностью изменения размеров областей",
                ["AboutTitle"] = "О программе",
                ["StatusModified"] = "Изменено",
                ["StatusReady"] = "Готово",
                ["Ln"] = "Ст",
                ["Col"] = "Ср",
                ["ResultTab_Output"] = "Вывод",
                ["ResultTab_Errors"] = "Ошибки",
                ["ResultTab_Stats"] = "Статистика",
                ["ErrorsGrid_Time"] = "Время",
                ["ErrorsGrid_Level"] = "Уровень",
                ["ErrorsGrid_Module"] = "Модуль",
                ["ErrorsGrid_Message"] = "Сообщение",
                ["ErrorsGrid_Code"] = "Код",
                ["ErrorLevel_Error"] = "Ошибка",
                ["ErrorLevel_Warning"] = "Предупреждение",
                ["ErrorLevel_Info"] = "Инфо",
                ["Errors_Clear"] = "Очистить ошибки",
                ["Errors_Copy"] = "Копировать сообщение",
                ["Errors_Export"] = "Экспорт в файл...",
                ["Errors_NoErrors"] = "Ошибки не обнаружены ✓"
            },
            ["en-US"] = new Dictionary<string, string>
            {
                ["AppName"] = "Text Editor",
                ["CodeGroup"] = "Code for execution",
                ["ResultGroup"] = "Execution result",
                ["FileMenu"] = "File",
                ["EditMenu"] = "Edit",
                ["HelpMenu"] = "Help",
                ["ViewMenu"] = "View",
                ["CreateMenu"] = "Create",
                ["OpenMenu"] = "Open",
                ["SaveMenu"] = "Save",
                ["SaveAsMenu"] = "Save As...",
                ["CloseMenu"] = "Close",
                ["ExitMenu"] = "Exit",
                ["UndoMenu"] = "Undo",
                ["RedoMenu"] = "Redo",
                ["CutMenu"] = "Cut",
                ["CopyMenu"] = "Copy",
                ["PasteMenu"] = "Paste",
                ["DeleteMenu"] = "Delete",
                ["SelectAllMenu"] = "Select All",
                ["UserGuideMenu"] = "User Guide",
                ["AboutMenu"] = "About",
                ["FontSizeMenu"] = "Font Size",
                ["LanguageMenu"] = "Interface Language",
                ["StartMenu"] = "Start",
                ["AnalyzeTooltip"] = "Run analysis",
                ["TokensGrid_Code"] = "Token Code",
                ["TokensGrid_Type"] = "Token Type",
                ["TokensGrid_Lexeme"] = "Lexeme",
                ["TokensGrid_Location"] = "Location",
                ["ErrorsGrid_Fragment"] = "Invalid Fragment",
                ["ErrorsGrid_Location"] = "Location",
                ["ErrorsGrid_Description"] = "Description",
                ["ErrorsSummaryTotal"] = "Total errors:",
                ["LocationLine"] = "line",
                ["LocationPosition"] = "position",
                ["AnalysisSuccess"] = "SUCCESS",
                ["AnalysisProcessedLexemes"] = "Processed {0} lexemes",
                ["Lexer_InvalidCharacter"] = "Invalid character: '{0}'",
                ["TokenType_Keyword"] = "keyword",
                ["TokenType_Identifier"] = "identifier",
                ["TokenType_Number"] = "number",
                ["TokenType_Operator"] = "operator",
                ["TokenType_Separator"] = "separator",
                ["TokenType_Whitespace"] = "whitespace",
                ["TokenType_Error"] = "error",
                ["TokenType_Unknown"] = "unknown",
                ["Parser_ExpectedPrefix"] = "Expected",
                ["Parser_ExpectedIdentifier"] = "identifier",
                ["Parser_ExpectedFloatNumber"] = "floating-point number",
                ["Parser_EmptyInput"] = "Empty input stream",
                ["Parser_WhitespaceOnlyInput"] = "Empty input stream (whitespace only)",
                ["Parser_InvalidFragment"] = "Invalid fragment",
                ["Parser_InvalidNumberFormat"] = "Invalid number format",
                ["Parser_ExpectedDigitAfterDecimal"] = "Expected a digit after the decimal point",
                ["Parser_ExpectedDigitAfterExponent"] = "Expected a digit after the exponent",
                ["ConfirmationExit"] = "Exit Confirmation",
                ["ConfirmationClose"] = "Close Confirmation",
                ["UnsavedChangesTab"] = "You have unsaved changes in tab",
                ["SaveBeforeExit"] = "Save before exit?",
                ["SaveBeforeClose"] = "Save before close?",
                ["ExitQuestion"] = "Exit?",
                ["UnsavedChangesPromptExit"] = "You have unsaved changes in tab '{0}'. Save before exit?",
                ["UnsavedChangesPromptClose"] = "You have unsaved changes in tab '{0}'. Save before close?",
                ["UserGuideTitle"] = "User Guide",
                ["FunctionsList"] = "Implemented functions:",
                ["CreateOpenSave"] = "- Creating, opening, saving files",
                ["TextOperations"] = "- Text operations: undo/redo, cut, copy, paste, delete",
                ["SelectAll"] = "- Select all text",
                ["FontSizeChange"] = "- Change font size",
                ["LineNumbering"] = "- Line numbering in edit window",
                ["MultiDocs"] = "- Working with multiple documents through tabs",
                ["AdaptiveInterface"] = "- Adaptive interface with possibility to change sizes of areas",
                ["AboutTitle"] = "About Program",
                ["StatusModified"] = "Modified",
                ["StatusReady"] = "Ready",
                ["Ln"] = "Ln",
                ["Col"] = "Col",
                ["ResultTab_Output"] = "Output",
                ["ResultTab_Errors"] = "Errors",
                ["ResultTab_Stats"] = "Statistics",
                ["ErrorsGrid_Time"] = "Time",
                ["ErrorsGrid_Level"] = "Level",
                ["ErrorsGrid_Module"] = "Module",
                ["ErrorsGrid_Message"] = "Message",
                ["ErrorsGrid_Code"] = "Code",
                ["ErrorLevel_Error"] = "Error",
                ["ErrorLevel_Warning"] = "Warning",
                ["ErrorLevel_Info"] = "Info",
                ["Errors_Clear"] = "Clear Errors",
                ["Errors_Copy"] = "Copy Message",
                ["Errors_Export"] = "Export to File...",
                ["Errors_NoErrors"] = "No errors detected ✓"
            }
        };

        private static string currentCulture = "ru-RU";

        public static void SwitchLanguage(string cultureCode)
        {
            currentCulture = cultureCode;
            Thread.CurrentThread.CurrentUICulture = new CultureInfo(cultureCode);
        }

        public static string GetCurrentCulture()
        {
            return currentCulture;
        }

        public static string GetString(string key)
        {
            if (languageResources.ContainsKey(currentCulture) && languageResources[currentCulture].ContainsKey(key))
            {
                return languageResources[currentCulture][key];
            }
            return key;
        }
    }
}
